site_name: MIX-Honor
site_url: https://mydomain.org/mysite
nav:
  - 主页: index.md
  - 混合课程: 
    - courses/index.md

  - 学院与专业: 
    - colleges/index.md
    - 计算机科学与技术学院:
      - colleges/cspo/index.md

    - 控制科学与工程学院:
      - colleges/cse/index.md

    - 信息与电子工程学院:
      - colleges/isee/index.md

    - 光电科学与工程学院:
      - colleges/opt/index.md

    - 电气工程学院:
      - colleges/ee/index.md

    - 机械工程学院:
      - colleges/me/index.md

    - 能源工程学院:
      - colleges/ode-oa/index.md

    - 生物医学工程与仪器科学学院:
      - colleges/cbeis/index.md
      
    - 其他:
      - colleges/others/index.md

  - 导师制: 
    - tutor/index.md

  - 科研训练: 
    - SRTP/index.md

  - 乐活混合: 
    - happy/index.md

  - 师长分享: 
    - share/index.md

  - 深造资讯: 
    - Fur-edu/index.md

theme: 
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.indexes

